import { db } from "../client";
import { listings, listingImages } from "../schema";
import { eq } from "drizzle-orm";
import { seedCommunities } from "./communities";

export const SEED_LISTINGS = [
  {
    slug: "sarvani-heights-3bhk",
    title: "3 BHK for rent in Sarvani Heights, Gachibowli",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 3,
    propertyType: "Apartment",
    areaSqft: 1450,
    floor: 7,
    totalFloors: 14,
    facing: "East",
    furnishing: "Semi-Furnished",
    price: 42000,
    deposit: 100000,
    maintenance: 3500,
    availableFrom: "2026-10-01",
    tenantPreference: ["Family", "Working Professionals"],
    amenities: ["Covered Parking", "Gym", "Swimming Pool", "Clubhouse", "24/7 Power Backup"],
    petFriendly: true,
    parking: true,
    communitySlug: "sarvani-heights",
    locality: "Gachibowli",
    city: "Hyderabad",
    description: "East-facing 3 BHK on the 7th floor overlooking landscaped gardens. Spacious modular kitchen, imported Italian marble in living areas, and high-efficiency VRV air conditioning. Verified on-site by HTC facility management team.",
    verifiedByName: "Ramesh Reddy (Facility Manager)",
    verifiedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-01", sortOrder: 0, alt: "Living room with natural light and balcony view" },
      { imageKey: "detail-gallery-02", sortOrder: 1, alt: "Master bedroom with attached balcony" },
      { imageKey: "detail-gallery-03", sortOrder: 2, alt: "Modern modular kitchen with granite countertop" },
      { imageKey: "detail-gallery-04", sortOrder: 3, alt: "Spacious dining area" },
      { imageKey: "detail-gallery-05", sortOrder: 4, alt: "Community amenities and garden walkway" },
    ],
  },
  {
    slug: "lanco-hills-residencies-2bhk",
    title: "2 BHK for rent in Lanco Hills Residencies, Manikonda",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 2,
    propertyType: "Apartment",
    areaSqft: 1100,
    floor: 12,
    totalFloors: 30,
    facing: "North-East",
    furnishing: "Fully Furnished",
    price: 28500,
    deposit: 60000,
    maintenance: 2500,
    availableFrom: "2026-09-25",
    tenantPreference: ["Family", "Company Lease"],
    amenities: ["Gym", "Tennis Court", "24/7 Security", "EV Charging"],
    petFriendly: false,
    parking: true,
    communitySlug: "lanco-hills-residencies",
    locality: "Manikonda",
    city: "Hyderabad",
    description: "High-floor 2 BHK offering skyline views of Manikonda hills. Fully furnished with premium teak wood furniture, smart appliances, and covered reserved car park.",
    verifiedByName: "Anil Kumar (HTC Operations)",
    verifiedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-02", sortOrder: 0, alt: "Living hall with high floor skyline view" },
      { imageKey: "detail-gallery-03", sortOrder: 1, alt: "Modern kitchen" },
    ],
  },
  {
    slug: "my-home-bhooja-3bhk",
    title: "3 BHK for rent in My Home Bhooja, HITEC City",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 3,
    propertyType: "Apartment",
    areaSqft: 1780,
    floor: 18,
    totalFloors: 36,
    facing: "West",
    furnishing: "Semi-Furnished",
    price: 55000,
    deposit: 150000,
    maintenance: 4500,
    availableFrom: "2026-10-15",
    tenantPreference: ["Family", "Expatriates"],
    amenities: ["Olympic Pool", "Badminton Court", "Spa", "Concierge"],
    petFriendly: true,
    parking: true,
    communitySlug: "my-home-bhooja",
    locality: "HITEC City",
    city: "Hyderabad",
    description: "Ultra-luxury high rise 3 BHK next to Biodiversity Park. Features double-height living room windows, Italian wardrobes, and dedicated EV charging bay.",
    verifiedByName: "Priya Sharma (HTC Senior Auditor)",
    verifiedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-03", sortOrder: 0, alt: "Spacious master suite" },
      { imageKey: "detail-gallery-01", sortOrder: 1, alt: "Living lounge" },
    ],
  },
  {
    slug: "aparna-serene-park-1bhk",
    title: "1 BHK for rent in Aparna Serene Park, Kondapur",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 1,
    propertyType: "Apartment",
    areaSqft: 650,
    floor: 4,
    totalFloors: 15,
    facing: "East",
    furnishing: "Fully Furnished",
    price: 19000,
    deposit: 40000,
    maintenance: 1800,
    availableFrom: "2026-09-22",
    tenantPreference: ["Single Executive", "Students"],
    amenities: ["Gym", "Jogging Track", "Clubhouse", "Intercom"],
    petFriendly: false,
    parking: true,
    communitySlug: "aparna-serene-park",
    locality: "Kondapur",
    city: "Hyderabad",
    description: "Compact, well-ventilated 1 BHK unit ideal for IT professionals working around Cyber Towers and Financial District.",
    verifiedByName: "Ramesh Reddy (Facility Manager)",
    verifiedAt: new Date(),
    images: [
      { imageKey: "detail-gallery-04", sortOrder: 0, alt: "Living and work corner" },
    ],
  },
  {
    slug: "jayabheri-the-summit-2bhk",
    title: "2 BHK for rent in Jayabheri The Summit, Nanakramguda",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 2,
    propertyType: "Apartment",
    areaSqft: 1250,
    floor: 9,
    totalFloors: 22,
    facing: "North",
    furnishing: "Semi-Furnished",
    price: 34000,
    deposit: 80000,
    maintenance: 3000,
    availableFrom: "2026-10-05",
    tenantPreference: ["Family"],
    amenities: ["Clubhouse", "Gym", "Landscaped Gardens", "Solar Water Heating"],
    petFriendly: true,
    parking: true,
    communitySlug: "jayabheri-the-summit",
    locality: "Nanakramguda",
    city: "Hyderabad",
    description: "Corner 2 BHK with cross ventilation and peaceful green views, 5 minutes from Financial District junction.",
    verifiedByName: "Anil Kumar (HTC Operations)",
    verifiedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-05", sortOrder: 0, alt: "Balcony and living hall" },
    ],
  },
  {
    slug: "smr-vinay-iconia-4bhk",
    title: "4 BHK Luxury Flat for rent in SMR Vinay Iconia, Kondapur",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 4,
    propertyType: "Apartment",
    areaSqft: 2100,
    floor: 15,
    totalFloors: 25,
    facing: "East",
    furnishing: "Fully Furnished",
    price: 67000,
    deposit: 180000,
    maintenance: 5000,
    availableFrom: "2026-10-01",
    tenantPreference: ["Family", "Executives"],
    amenities: ["Cricket Pitch", "Swimming Pool", "Gym", "Grocery Store"],
    petFriendly: true,
    parking: true,
    communitySlug: "smr-vinay-iconia",
    locality: "Kondapur",
    city: "Hyderabad",
    description: "Palatial 4 BHK with servant room, expansive open balcony, state-of-the-art kitchen, and multiple parking slots.",
    verifiedByName: "Ramesh Reddy (Facility Manager)",
    verifiedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-01", sortOrder: 0, alt: "Expansive living room" },
    ],
  },
  {
    slug: "rajapushpa-atria-1bhk",
    title: "1 BHK for rent in Rajapushpa Atria, Kokapet",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 1,
    propertyType: "Apartment",
    areaSqft: 600,
    floor: 6,
    totalFloors: 18,
    facing: "East",
    furnishing: "Semi-Furnished",
    price: 24000,
    deposit: 50000,
    maintenance: 2000,
    availableFrom: "2026-09-28",
    tenantPreference: ["Single Executive", "Working Couple"],
    amenities: ["Rooftop Lounge", "Infinity Pool", "Squash Court", "Gym"],
    petFriendly: false,
    parking: true,
    communitySlug: "rajapushpa-atria",
    locality: "Kokapet",
    city: "Hyderabad",
    description: "Chic modern 1 BHK in high demand Kokapet corridor. Includes access to clubhouse infinity pool and rooftop co-working hub.",
    verifiedByName: "Priya Sharma (HTC Senior Auditor)",
    verifiedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-02", sortOrder: 0, alt: "Bedroom interior" },
    ],
  },
  {
    slug: "candeur-landmark-3bhk",
    title: "3 BHK for rent in Candeur Landmark, Financial District",
    intent: "rent" as const,
    status: "active" as const,
    bhk: 3,
    propertyType: "Apartment",
    areaSqft: 1500,
    floor: 11,
    totalFloors: 24,
    facing: "North-West",
    furnishing: "Semi-Furnished",
    price: 39000,
    deposit: 90000,
    maintenance: 3200,
    availableFrom: "2026-10-10",
    tenantPreference: ["Family"],
    amenities: ["Gym", "Co-working Space", "Badminton Court", "Security"],
    petFriendly: true,
    parking: true,
    communitySlug: "candeur-landmark",
    locality: "Financial District",
    city: "Hyderabad",
    description: "Well-appointed 3 BHK within walking distance to leading tech parks in Financial District. Excellent natural ventilation.",
    verifiedByName: "Anil Kumar (HTC Operations)",
    verifiedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    images: [
      { imageKey: "detail-gallery-03", sortOrder: 0, alt: "Master bedroom" },
    ],
  },
];

export async function seedListings(communityMap: Map<string, string>) {
  console.log("Seeding listings...");

  for (const item of SEED_LISTINGS) {
    const existing = await db
      .select({ id: listings.id })
      .from(listings)
      .where(eq(listings.slug, item.slug))
      .limit(1);

    const communityId = communityMap.get(item.communitySlug);

    let listingId: string;

    if (existing.length > 0) {
      listingId = existing[0].id;
      console.log(`Listing exists: ${item.slug}`);
      await db
        .update(listings)
        .set({
          title: item.title,
          intent: item.intent,
          status: item.status,
          bhk: item.bhk,
          propertyType: item.propertyType,
          areaSqft: item.areaSqft,
          floor: item.floor,
          totalFloors: item.totalFloors,
          facing: item.facing,
          furnishing: item.furnishing,
          price: item.price,
          deposit: item.deposit,
          maintenance: item.maintenance,
          availableFrom: item.availableFrom,
          tenantPreference: item.tenantPreference,
          amenities: item.amenities,
          petFriendly: item.petFriendly,
          parking: item.parking,
          communityId: communityId || null,
          locality: item.locality,
          city: item.city,
          description: item.description,
          verifiedByName: item.verifiedByName,
          verifiedAt: item.verifiedAt,
          publishedAt: new Date(),
        })
        .where(eq(listings.id, listingId));
    } else {
      const [inserted] = await db
        .insert(listings)
        .values({
          slug: item.slug,
          title: item.title,
          intent: item.intent,
          status: item.status,
          bhk: item.bhk,
          propertyType: item.propertyType,
          areaSqft: item.areaSqft,
          floor: item.floor,
          totalFloors: item.totalFloors,
          facing: item.facing,
          furnishing: item.furnishing,
          price: item.price,
          deposit: item.deposit,
          maintenance: item.maintenance,
          availableFrom: item.availableFrom,
          tenantPreference: item.tenantPreference,
          amenities: item.amenities,
          petFriendly: item.petFriendly,
          parking: item.parking,
          communityId: communityId || null,
          locality: item.locality,
          city: item.city,
          description: item.description,
          verifiedByName: item.verifiedByName,
          verifiedAt: item.verifiedAt,
          publishedAt: new Date(),
        })
        .returning({ id: listings.id });
      listingId = inserted.id;
      console.log(`Created listing: ${item.slug}`);
    }

    // Seed listing images
    await db.delete(listingImages).where(eq(listingImages.listingId, listingId));
    for (const img of item.images) {
      await db.insert(listingImages).values({
        listingId,
        imageKey: img.imageKey,
        sortOrder: img.sortOrder,
        alt: img.alt,
      });
    }
  }
}
